title: <p align="center">About Me</p>

logo: /assets/img/siv_pic.png

description: |
  <p align="center">
  <a href="docs/Sivamani_Resume.pdf">Resume</a> | 
  <a href="https://www.linkedin.com/in/sivamanir/">LinkedIn</a> | 
  <a href="https://github.com/Rsivamani">GitHub</a>


  <br><br>
  I’m an AI Engineer focused on building practical AI and Machine Learning
  solutions using Python, Generative AI, LLMs, RAG, and NLP.
  <br><br>
  I build end-to-end AI applications, from data preprocessing and model
  development to embeddings, vector search, retrieval pipelines, and
  FastAPI-based AI systems.
  <br><br>
  📱 <strong>Mobile:</strong> +91 8754273235
  <br>
  📧 <strong>Email:</strong> sivamanirajendran.m@gmail.com

